// Package users is a DAO(Data Access Object)
package users

import (
	"fmt"
	"github.com/Gunnsteinn/Go-Study/Rest_microservices/bookstore_users-api/datasources/mysql/users_db"
	"github.com/Gunnsteinn/Go-Study/Rest_microservices/bookstore_users-api/utils/errors"
	"github.com/Gunnsteinn/Go-Study/Rest_microservices/bookstore_users-api/utils/mysql_utils"
)

const (
	queryInsertUser       = "INSERT INTO users(first_name,last_name,email,date_created,status,password) VALUES( ?, ?, ?, ?, ?, ?);"
	queryGetUser          = "SELECT id,first_name,last_name,email,date_created,status FROM users WHERE id=?;"
	queryUpdateUser       = "UPDATE users SET first_name=?,last_name=?,email=? WHERE id=?;"
	queryDeleteUser       = "DELETE FROM users WHERE id=?;"
	queryFindUserByStatus = "SELECT id,first_name,last_name,email,date_created,status FROM users WHERE status=?;"
)

// Get method implements User struct and get user from the db.
func (user *User) Get() *errors.RestErr {
	// Prepare creates a prepared statement for later queries or executions.
	stmt, err := users_db.Client.Prepare(queryGetUser)
	if err != nil {
		return errors.NewInternalServerError(err.Error())
	}
	// The caller must call the statement's Close method.
	defer stmt.Close()

	// QueryRow executes a prepared query statement with the given arguments and return user data base value.
	result := stmt.QueryRow(user.ID)
	if getErr := result.Scan(&user.ID, &user.FirstName, &user.LastName, &user.Email, &user.DateCreated, &user.Status); getErr != nil {
		return mysql_utils.ParseError(getErr)
	}
	return nil
}

// Save method implements the User struct and saves the user to the database.
func (user *User) Save() *errors.RestErr {
	// Prepare creates a prepared statement for later queries or executions.
	stmt, err := users_db.Client.Prepare(queryInsertUser)
	if err != nil {
		return errors.NewInternalServerError(err.Error())
	}
	// The caller must call the statement's Close method.
	defer stmt.Close()

	// Exec persist data user in DB.
	insertResult, saveErr := stmt.Exec(user.FirstName, user.LastName, user.Email, user.DateCreated, user.Status, user.Password)
	if saveErr != nil {
		return mysql_utils.ParseError(saveErr)
	}

	// LastInsertId returns the integer generated by the database.
	userID, err := insertResult.LastInsertId()
	if err != nil {
		return mysql_utils.ParseError(err)
	}
	user.ID = userID
	return nil
}

// Update method implements the User struct and update the user to the database.
func (user *User) Update() *errors.RestErr {
	// Prepare creates a prepared statement for later queries or executions.
	stmt, err := users_db.Client.Prepare(queryUpdateUser)
	if err != nil {
		return errors.NewInternalServerError(err.Error())
	}
	// The caller must call the statement's Close method.
	defer stmt.Close()

	// Exec update data user in DB.
	_, updateErr := stmt.Exec(user.FirstName, user.LastName, user.Email, user.ID)
	if updateErr != nil {
		return mysql_utils.ParseError(updateErr)
	}
	return nil
}

// Delete method implements User struct and delete user from the db.
func (user *User) Delete() *errors.RestErr {
	// Prepare creates a prepared statement for later queries or executions.
	stmt, err := users_db.Client.Prepare(queryDeleteUser)
	if err != nil {
		return errors.NewInternalServerError(err.Error())
	}
	// The caller must call the statement's Close method.
	defer stmt.Close()

	// Exec delete data user in DB.
	if _, deleteErr := stmt.Exec(user.ID); deleteErr != nil {
		return mysql_utils.ParseError(deleteErr)
	}
	return nil
}

// FindByStatus method implements User struct and find by status user from the db.
func (user *User) FindByStatus(status string) ([]User, *errors.RestErr) {
	// Prepare creates a prepared statement for later queries or executions.
	stmt, err := users_db.Client.Prepare(queryFindUserByStatus)
	if err != nil {
		return nil, errors.NewInternalServerError(err.Error())
	}
	// The caller must call the statement's Close method.
	defer stmt.Close()

	//
	rows, FindErr := stmt.Query(status)
	if FindErr != nil {
		return nil, errors.NewInternalServerError(FindErr.Error())
	}
	defer rows.Close()

	//
	results := make([]User, 0)
	for rows.Next() {
		var user User
		if err := rows.Scan(&user.ID, &user.FirstName, &user.LastName, &user.Email, &user.DateCreated, &user.Status); err != nil {
			return nil, mysql_utils.ParseError(err)
		}
		results = append(results, user)
	}
	if len(results) == 0 {
		return nil, errors.NewNotFoundError(fmt.Sprintf("no users matching status %s", status))
	}
	return results, nil
}
